---
spring:
  profiles: peer1
  application:
    name: eureka-server-ha
server:
  port: 8761
eureka:
  server:
      enable-self-preservation: false
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance-id:${server.port}}
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/

---
spring:
  profiles: peer2
  application:
    name: eureka-server-ha
server:
  port: 8762
eureka:
  server:
      enable-self-preservation: false
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance-id:${server.port}}
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/

---
spring:
  profiles: peer3
  application:
    name: eureka-server-ha
server:
  port: 8763
eureka:
  server:
      enable-self-preservation: false
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance-id:${server.port}}
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/