spring:
  application:
    name: admin-client-register-security-server
  boot:
    admin:
      client:
        url: http://127.0.0.1:8787
        username: admin
        password: admin
server:
  port: 8788
management:
  endpoints:
    web:
      exposure:
        include: '*'
