spring:
  application:
    name: eureka-server
server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance-id:${server.port}}
    hostname: ${spring.cloud.client.hostname}
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/