spring:
  application:
    name: ribbon-retry
server:
  port: 9094
eureka:
  instance:
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
eureka-client-common:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule
    max-auto-retries: 1
    max-auto-retries-next-server: 3
    ok-to-retry-on-all-operations: true