spring:
  application:
    name: gateway-ssl
  cloud:
    gateway:
      httpclient:
        ssl:
          # 信任所有下游证书(生产环境不建议使用)
          # useInsecureTrustManager: true
          # 指定受信任的证书
          trustedX509Certificates:
          - cert1.pem
          - cert2.pem

server:
  port: 9080
  # 网关支持 https
  ssl:
    enabled: true
    key-alias: scg
    key-store-password: scg1234
    key-store: classpath:scg-keystore.p12
    key-store-type: PKCS12
eureka:
  instance:
    # instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance-id:${server.port}}
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]