spring:
  application:
    name: gateway-global-filter
  cloud:
    gateway:
      # 默认过滤器
      default-filters:
      - AddRequestParameter=name, guolanren
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar

      routes:
      - id: hello
        uri: lb://eureka-client
        predicates:
        - Path=/hello

server:
  port: 9080
eureka:
  instance:
    # instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance-id:${server.port}}
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]