spring:
  application:
    name: ribbon-single
server:
  port: 9094
ribbon:
  eureka:
    enabled: false
eureka-client-common:
  ribbon:
    listOfServers: http://localhost:9090,http://localhost:9091
#    NFLoadBalancerRuleClassName: name.guolanren.component.MyRule
#    NFLoadBalancerPingClassName: name.guolanren.component.MyPing