spring:
  application:
    name: ribbon-eureka
server:
  port: 9094
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance-id:${server.port}}
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown,service-registry