spring:
  application:
    name: gateway-predicate
server:
  port: 9080
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance-id:${server.port}}
    hostname: ${spring.cloud.client.hostname}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "hystrix.stream", "routes", "filters"]

spring:
  cloud:
    gateway:
      routes:
      - id: hello
        uri: lb://eureka-client
        predicates:
        - Path=/hello
        - After=2007-12-03T10:15:30+01:00[Europe/Paris]
      - id: hell
        uri: lb://eureka-client
        predicates:
        - Path=/hell
        - Before=2007-12-03T10:15:30+01:00[Europe/Paris]