spring:
  application:
    name: gateway-predicate
  cloud:
    gateway:
      routes:
      - id: after
        uri: lb://eureka-client-common
        predicates:
        - Path=/hello
        - After=2007-12-03T10:15:30+01:00[Europe/Paris]
      - id: before
        uri: lb://eureka-client-common
        predicates:
        - Path=/hell
        - Before=2007-12-03T10:15:30+01:00[Europe/Paris]

server:
  port: 9080
eureka:
  instance:
#    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance-id:${server.port}}
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]