spring:
  application:
    name: gateway-filter

server:
  port: 9080
eureka:
  instance:
#    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance-id:${server.port}}
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "hystrix.stream", "routes", "filters"]


spring:
  cloud:
    gateway:
      # 默认过滤器
      default-filters:
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      - PrefixPath=/httpbin
      routes:
      - id: add_request_header
        uri: lb://eureka-client
        predicate:
        - Path=/hello/{who}
        filters:
        - AddRequestHeader=WHO, {who}
      filter:
        remove-hop-by-hop:
          headers: Connection,Keep-Alive,Proxy-Authenticate,Proxy-Authorization,TE,Trailer,Transfer-Encoding,Upgrade
        secure-headers:
          disable: frame-options,download-options