spring:
  application:
    name: hystrix-turbine
server:
  port: 8771
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance-id:${server.port}}
    hostname: ${spring.cloud.client.hostname}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
turbine:
  aggregator:
    clusterConfig: HYSTRIX-DASHBOARD
  appConfig: hystrix-dashboard